### ISSUE TITLE
RS256 algorithm not supported

### ISSUE THREAD

**Issue by jessedobbelaere** [choffmeister/Paw-JsonWebTokenDynamicValue#4]
While the paw docs say that RS256 is supported, it does seem to give errors when I try it. 
Any reason why this would happen? Is it not supported?

https://paw.cloud/docs/auth/jwt

![screen shot 2017-02-13 at 17 54 32](https://cloud.githubusercontent.com/assets/1352979/22893274/82ef03fe-f215-11e6-9152-3a4b18e48251.png)

When I change it back to HS256, everything works.

**Comment by DigitalD1982** [comment]
I'm having this problem as well. How did you fix this @jessedobbelaere ?

**Comment by jessedobbelaere** [comment]
@DigitalD1982 I don't have the issue anymore. Not really sure what changed or maybe it was my settings. This is what I currently use every day in Paw to authenticate to my api with JWT, it might help you:

![screen shot 2017-09-06 at 00 02 57](https://user-images.githubusercontent.com/1352979/30085477-e8f2d4e2-9296-11e7-8421-60d7ddf487af.png)
